import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { UserData } from './user.types';

// Define the type for the user state.
export type UserState = {
  readonly currentUser: UserData | null; // currentUser can be UserData or null, and is read-only.
  readonly test: { a: number }; // A test property with a nested object, also read-only.
};

// Define the initial state for the user slice.
const INITIAL_STATE: UserState = {
  currentUser: null, // Initially, no user is logged in.
  test: { a: 1 }, // Initial value for the test property.
};

// Create a Redux slice using createSlice.
export const userSlice = createSlice({
  name: 'user', // The name of the slice, used as a prefix for generated action types.
  initialState: INITIAL_STATE, // The initial state for this slice.
  reducers: {
    // Define reducer functions that handle state updates.
    // Each function corresponds to an action type.
    setCurrentUser(state, action: PayloadAction<UserData | null>) {
      // This reducer updates the currentUser property of the state.
      // It takes the current state and an action with a payload of type UserData or null.
      state.currentUser = action.payload; // Directly mutate the state thanks to Immer, which is used internally by Redux Toolkit.
    },
  },
});

// Export the action creators generated by createSlice.
// These are functions that return action objects.
export const { setCurrentUser } = userSlice.actions;

// Export the reducer function generated by createSlice.
// This reducer will be combined with other reducers in the store.
export const userReducer = userSlice.reducer;
