import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { Category } from './category.types';

// Define the shape of the categories state
export type CategoriesState = {
  readonly categories: Category[]; // An array of Category objects
};

// Define the initial state for the categories slice
export const CATEGORIES_INITIAL_STATE: CategoriesState = {
  categories: [], // Initialize categories as an empty array
};

// Create a Redux slice for categories using createSlice from @reduxjs/toolkit
export const categoriesSlice = createSlice({
  name: 'categories', // The name of the slice, used as a prefix for action types
  initialState: CATEGORIES_INITIAL_STATE, // The initial state for this slice
  reducers: {
    // Define a reducer function to set the categories
    setCategories(state, action: PayloadAction<Category[]>) {
      // Immer allows direct mutation of the state inside createSlice reducers
      // The payload (action.payload) is expected to be an array of Category objects
      state.categories = action.payload;
    },
  },
});

// Destructure and export the action creator(s) generated by createSlice
export const { setCategories } = categoriesSlice.actions;

// Export the reducer function generated by createSlice
export const categoriesReducer = categoriesSlice.reducer;
